/**************************************************************  
 *               MTOOLS CONFIGURATION FILE                    *  
 *                                                            *  
 * This file is automatically generated by the cmake script   *  
 **************************************************************/ 
 
#pragma once 
 
#define MTOOLS_VERSION 3
 
#define MTOOLS_BASIC_CONSOLE 0
 
#define MTOOLS_USE_SSE 0 
/* #undef MTOOLS_SSE_VERSION */
 
#define MTOOLS_USE_OPENMP 1 
#define MTOOLS_OPENMP_VERSION 2.0 

#define MTOOLS_USE_OPENCL 1 
#define MTOOLS_OPENCL_VERSION 1.2 

#define MTOOLS_USE_OPENGL 1 

 
/* end of mtools_config.hpp */            
 
