/**************************************************************  
 *               MTOOLS CONFIGURATION FILE                    *  
 *                                                            *  
 * This file is automatically generated by the cmake script   *  
 **************************************************************/ 
 
#pragma once 
 
#define MTOOLS_VERSION 3
 
#define MTOOLS_BASIC_CONSOLE 0
 
#define MTOOLS_USE_SSE 0 
 
#define MTOOLS_USE_OPENMP 0 

#define MTOOLS_USE_OPENCL 0 

#define MTOOLS_USE_OPENGL 1 

 
/* end of mtools_config.hpp */            
 
