# - Try to find the cairo library
# Once done this will define
#
#  CAIRO_FOUND and CAIRO_alt_FOUND - system has cairo
#  CAIRO_INCLUDE_DIRS - the cairo include directory
#  CAIRO_LIBRARIES - Link these to use cairo
#
# Define CAIRO_MIN_VERSION for which version desired.
#

find_package(PkgConfig)

IF (PKG_CONFIG_FOUND)
	PKG_SEARCH_MODULE(CAIRO cairo)
ENDIF(PKG_CONFIG_FOUND)

IF(NOT CAIRO_FOUND AND NOT PKG_CONFIG_FOUND)
	FIND_PATH(CAIRO_INCLUDE_DIRS cairo.h)
	FIND_LIBRARY(CAIRO_LIBRARIES cairo)

	# Report results
	IF(CAIRO_LIBRARIES AND CAIRO_INCLUDE_DIRS)
		SET(CAIRO_FOUND 1)
		MESSAGE(STATUS "Found Cairo: ${CAIRO_LIBRARIES}")
	ELSE(CAIRO_LIBRARIES AND CAIRO_INCLUDE_DIRS)	
		MESSAGE(SEND_ERROR "Could not find Cairo")
	ENDIF(CAIRO_LIBRARIES AND CAIRO_INCLUDE_DIRS)
ENDIF(NOT CAIRO_FOUND AND NOT PKG_CONFIG_FOUND)

IF (CAIRO_FOUND)
	SET(CAIRO_alt_FOUND 1)
ENDIF()	

# Hide advanced variables from CMake GUIs
MARK_AS_ADVANCED(CAIRO_LIBRARIES CAIRO_INCLUDE_DIRS)
